### ISSUE TITLE
Connecting react-draggable elements

### ISSUE THREAD

**Issue by j1m-renwick** [uladkasach/react-simple-arrows#1]
I'm attempting to use this library to draw an arrow connecting two draggable elements on a page (which use https://www.npmjs.com/package/react-draggable).  

The react-draggable package has some onDrag etc. hooks I can use for updating components, but before I go down a rabbit-hole of trying to track and update the arrow components myself, I was wondering if there was any native functionality in this package (maybe that I've overlooked) that you think could be of use?

**Comment by uladkasach** [comment]
Hey @j1m-renwick - sorry i'm seeing this so late. Since the "ref" will update any time your component moves - by idea you shouldn't need to do anything special for the arrows to update on each render. That should already be handled.
